service: express-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
        - "apigateway:*"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource: "*"

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
  deploymentBucket:
    name: serverless-deployment-bucket-${self:provider.region}

